### ISSUE TITLE
Add extra skills in DB

### ISSUE THREAD

**Issue by sak007** [sak007/Jobby#12]
Insert more skills in skill_master table.
schema path
<home>/Code/Database/schema/srijas.sql

**Comment by sak007** [comment]
Insert more skills in skill_master table

**Comment by sak1997** [comment]
Added 10 - 15 new skills there now

**Comment by sak007** [comment]
Have to add few more skills

**Comment by sak1997** [comment]
I'll check and see what we can do. I haven't been able to find a dataset for this online. Also, if we add to much data, don't we risk add too much data into the database? 

How many posting do you get with the current data? Can you please try running the scrapers with this once?

**Comment by sak1997** [comment]
Added a few more skills through the indeed scraper branch - please review those and let me know if we need even more
